server:
  port: 8081

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/crypto}
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/arquitectura
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs

api:
  url: https://api.coincap.io/v2/assets
  auth: http://localhost:8080/realms/arquitectura/protocol/openid-connect/token

token:
  converter:
    principal-attribute: preferred_username
    resource-id: frontend