POST http://localhost:8080/api/v1/cryptocurrency
Content-Type: application/json

{
    "name": "litecoin"
}


###
GET http://localhost:8081/api/v1/cryptocurrency?page=0&size=5

###
PUT http://localhost:8080/api/v1/cryptocurrency/1

###
PUT http://localhost:8080/api/v1/cryptocurrency/2/price
Content-Type: application/json

{
    "currentPrice": 909009
}


