POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
    "username": "Juan Perez",
    "email": "juan@email.com",
    "balance": 10200.32
}

###
PUT http://localhost:8080/api/v1/user/2


###
PUT http://localhost:8080/api/v1/user/3/balance
Content-Type: application/json

{
    "balance":922299
}